# Generated by Django 4.1.6 on 2023-02-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certassign',
            name='initial_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fwassign',
            name='initial_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mailgireassign',
            name='initial_date',
            field=models.DateField(),
        ),
    ]
