# Generated by Django 4.1.6 on 2023-02-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0002_alter_certassign_initial_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='certassign',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='fwassign',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='mailgireassign',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='certassign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fwassign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mailgireassign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='certassign',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_app.paioperator'),
        ),
        migrations.AddField(
            model_name='fwassign',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_app.paioperator'),
        ),
        migrations.AddField(
            model_name='mailgireassign',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_app.paioperator'),
        ),
    ]
