# Generated by Django 4.1.6 on 2023-02-13 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0003_paioperator_remove_certassign_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.IntegerField()),
                ('incident_state', models.CharField(default='Open', max_length=32)),
                ('registration_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('review_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel_app.paioperator')),
            ],
        ),
    ]
