# Generated by Django 4.1.6 on 2023-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0004_incidentmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmanagement',
            name='incident_comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
