# Generated by Django 4.1.7 on 2023-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0005_incidentmanagement_incident_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmanagement',
            name='incident_state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Progress', 'Progress')], default='Open', max_length=32),
        ),
    ]
