# Generated by Django 4.1.7 on 2023-02-25 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0006_alter_incidentmanagement_incident_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 25, 13, 19, 50, 657019, tzinfo=datetime.timezone.utc)),
        ),
    ]
