# Generated by Django 4.1.7 on 2023-02-26 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0008_incidentmanagement_resolution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 26, 14, 26, 0, 511418, tzinfo=datetime.timezone.utc)),
        ),
    ]
