# Generated by Django 4.1.7 on 2023-03-02 19:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_app', '0009_alter_incidentmanagement_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 2, 16, 2, 8, 914425, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='incidentmanagement',
            name='review_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
