# Generated by Django 4.1.7 on 2023-03-09 22:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel_app', '0013_remove_incidentmanagement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmanagement',
            name='case_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 9, 19, 24, 42, 734090, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='incidentmanagement',
            name='review_operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_operator', to=settings.AUTH_USER_MODEL),
        ),
    ]
