# Generated by Django 4.1.7 on 2023-03-09 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0014_incidentmanagement_case_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentmanagement',
            old_name='priority_case',
            new_name='case_priority',
        ),
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 9, 19, 46, 47, 852381, tzinfo=datetime.timezone.utc)),
        ),
    ]
