# Generated by Django 4.1.7 on 2023-03-09 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0016_alter_incidentmanagement_case_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmanagement',
            name='case_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 9, 19, 55, 43, 48904, tzinfo=datetime.timezone.utc)),
        ),
    ]
