# Generated by Django 4.2.1 on 2023-09-30 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0019_rename_publication_casecomment_case_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmanagement',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 30, 21, 4, 46, 496421, tzinfo=datetime.timezone.utc)),
        ),
    ]
